- src/components/StepFour.jsx
- src/data/states.json
Jira Ticket: https://bixal-projects.atlassian.net/browse/VOTE-1625
Implemented the design of the NVRF web form. This step includes:
- Display/hide NVRF fields based on state requirements
- Display/hide fields based on selection"new registration" or "change registration" paths
- Display/hide extra field groups for name and address based on checkbox states
-Create select drop downs for fields that benefit from set option list
This step does not include processing the PDF. It also includes some hardcoded values that will need to be replaced once step 3 is complete.
> Vote 1625/step four form fields

- src/components/FormSections/Identification.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/components/FormSections/ValidateField.jsx
[VOTE-52](https://cm-jira.usa.gov/browse/VOTE-52)
[VOTE-236](https://cm-jira.usa.gov/browse/VOTE-236)
Testing steps from tickets:
Steps to test month required:
- Try to move forward from Personal Information page without filling out month field
- Select "State ID Number" on Identification page
- Test moving forward without month field values complete
Steps to test tab trapping issue:
- Click in the name field and tab to the DOB fields
- Try to tab back to the name fields or tab forward to the phone number
Steps to test ability to edit input value with arrow keys:
- Click into the DOB field
- Enter 12 21 2101
- use arrow keys + delete to change year to 2021
> VOTE-52 & VOTE-236: fix tabbing bugs and require month attributes

- src/components/FormSections/PersonalInfo.jsx
- src/components/GenerateFilledPDF.jsx
- src/components/MultiStepForm.jsx
- src/components/RegTypes/NotNeeded.jsx
> VOTE-135 resolve console log errors

- src/components/FormSections/Confirmation.jsx
- src/components/MultiStepForm.jsx
https://cm-jira.usa.gov/browse/VOTE-277
> VOTE-277 Add edit buttons to confirm page

- src/components/FormSections/Identification.jsx
- src/components/MultiStepForm.jsx
- src/main.jsx
- src/styles/global.css
[VOTE-276](https://cm-jira.usa.gov/browse/VOTE-276)
> VOTE-276: fixes validation bugs and input styling

- src/components/FormSections/Confirmation.jsx
- src/components/FormSections/Delivery.jsx
- src/components/FormSections/PoliticalParty.jsx
- src/components/GenerateFilledPDF.jsx
- src/components/RegTypes/EligibilityCheckboxes.jsx
- src/data/states.json
ticket: [Vote-358](https://cm-jira.usa.gov/browse/VOTE-358)
Purpose:  This Pr will update the final page to render the correct state address.  There was a hard-coded address for Alaska and took that out and added a few new variables from the json file to render it based on the state that the user selected 
also, there were a few spelling errors that were fixed.. one had a whole line that was not being rendered and was fixed 
to test:
visit the prototype on this branch and fill out for `Maine` and `Alaska` and ensure that the address is correct
> Vote-358: Address Update

- src/components/GenerateFilledPDF.jsx
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-375
The PDF opens in a new tab without downloading.
Testing steps:
1. Fill out all form fields (don't skip any sections)
2. Submit and verify the PDF opens in a new tab with all fields correctly filled out
3. Verify the pdf does not save to your machine
> VOTE-375 Open PDF in new tab

- src/components/FormSections/Confirmation.jsx
- src/components/GenerateFilledPDF.jsx
https://cm-jira.usa.gov/browse/VOTE-379
CHANGELOG:
VOTE-339 hide expire date on confirmation if the field is empty
VOTE-375 open prefilled PDF in new window
> Sprint 43: release to MAIN

- .circleci/config.yml
[VOTE-289 Jira Ticket](https://cm-jira.usa.gov/browse/VOTE-289)
Create a job that pulls the NVRF from the EAC website and replaces the current PDF in the repo.
Check the linked circleci job below.
This will be the first PR to commit the circleci script to stage.
> VOTE-289 Create job to update the NVRF and create a PR

- src/components/FormSections/Addresses.jsx
- src/components/FormSections/Identification.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/styles/pages/Form.css
[VOTE-333](https://cm-jira.usa.gov/browse/VOTE-333)
this pr makes adjustments to the form layout and mobile stacking
> VOTE-333: add grid layout

- src/components/FormSections/Identification.jsx
- src/data/registration-form.json
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-462
Updates made to the identification page display based on the ID type. Verify the behavior matches Craig's designs.
> Feature/vote 462/identification section updates

- .circleci/config.yml
Jira Ticket:
Schedule NVRF job to run weekly on the stage branch
> VOTE-477 Run update-nvrf weekly on Friday, from stag

- package-lock.json
- package.json
- vite.config.js
No functional change should happen. This is only for preparing it to be embedded in another app.
> VOTE-246 update nvrf for embed compatibility

- public/data/en/states.json
- src/components/FormSections/Delivery.jsx
- src/components/GenerateFilledPDF.jsx
Jira Ticket: https://cm-jira.usa.gov/browse/VOTE-540
Confirm for both Alaska and Maine that only the following pages are part of the PDF:
1. Cover Page
2. National instructions
3. Set of filled NVRF fields
4. Set of unfilled NVRF fields
5. Pages of corresponding state instructions
> Feature/vote 540/remove nvrf pdf pages

- src/components/FormSections/Addresses.jsx
- src/components/MultiStepForm.jsx
clears mailing fields when not in use
> VOTE-586: fix checkbox bug on mailing address fields

- public/data/en/states.json
Added missing nvrf page list from Alaska
> Add missing nvrf_pages_list

- src/components/FormSections/PersonalInfo.jsx
[VOTE-630](https://cm-jira.usa.gov/browse/VOTE-630)
> VOTE-630: fix validation on race field required

- public/data/en/pages.json
Fix the USA.gov link on the "in-person" registration only page.
> VOTE-669 USA.gov voting link bug

- testing/cypress/e2e/tests/inPerson.cy.js
- testing/cypress/e2e/tests/online.cy.js
- testing/cypress/e2e/tests/verifyErrors.cy.js
- testing/cypress/support/commands.js
Purpose: Update to cypress test for the fixed state id string 
Ticket: [Vote-672](https://cm-jira.usa.gov/browse/VOTE-672)
Testing: Check that Cypress tests are passing in circleci run
> Vote-672: Cypress update to id page

- package-lock.json
- package.json
Purpose: This Pr will add updates from Snyk and adds no package-lock file as well. 
Ticket: [Vote-660](https://cm-jira.usa.gov/browse/VOTE-660)
Testing: Check that Snyk is not flagging aything, also pull down local and run the following commands and ensure no build errors `npm run install` and `npm run build`
Closes out: https://github.com/usagov/vote-gov-nvrf-app/pull/97, https://github.com/usagov/vote-gov-nvrf-app/pull/96, https://github.com/usagov/vote-gov-nvrf-app/pull/94, https://github.com/usagov/vote-gov-nvrf-app/pull/95
> Vote-660: Snyk Updates

- src/App.jsx
[VOTE-592](https://cm-jira.usa.gov/browse/VOTE-592)
> VOTE-592: add OMB and PRA info

- public/data/en/pages.json
This Pr will update the links on the landing page to open in a new tab.  This was pulled from the CMS and is updating the json file
> Vote-666: Fix to links opening into a new tab

- public/data/en/states.json
- src/components/GenerateFilledPDF.jsx
JIra: https://cm-jira.usa.gov/browse/VOTE-618
1. Remove the "no id" option from the Utah state data
2. Correct the ssn id option
> Bug/vote 618/utah id page

- public/data/en/states.json
- public/theme/assets/styles/nvrf.css
- src/components/FormSections/Confirmation.jsx
- src/components/GenerateFilledPDF.jsx
VOTE-724 style revisions
VOTE-618 solve Utah unique case id step
> HOTFIX release: Sprint 51

- public/data/en/pages.json
- public/data/en/states.json
- src/components/RegType/OnlineNoStateMail.jsx
- src/components/RegistrationOptions.jsx
Jira: https://cm-jira.usa.gov/browse/VOTE-758
Select California, and confirm the following on the registration page:
1. Online section displays
2. Mail NVRF section displays
3. State mail section **does not** display
4. Confirm section displays
> vote 758/no state mail template

- .circleci/config.yml
Update the PDF job to switch to the ongoing branch before making a PR.
This will have to be tested on STAGE.
> VOTE-658 Checkout the update-nvrf-pdf branch

- src/components/FormSections/PersonalInfo.jsx
[VOTE-743](https://cm-jira.usa.gov/browse/VOTE-743)
> VOTE-743: title/suffix select bug

- testing/cypress/e2e/tests/inPerson.cy.js
- testing/cypress/e2e/tests/online.cy.js
- testing/cypress/e2e/tests/verifyErrors.cy.js
- testing/cypress/support/commands.js
This Pr will update some text changes and formatting that happened within the app
> Vote-793: Cypress Updates

- src/App.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/components/MultiStepForm.jsx
- src/components/NextButton.jsx
Purpose:  This Pr will fix a bug on mobile that would not take the user back to the top of the page between eligibility and path selection pages. 
Ticket: [Vote-732](https://cm-jira.usa.gov/browse/VOTE-732)
Testing: 
1. Visit [preview link](https://federalist-aef5b597-8e18-44b6-aeba-3fc3f17cdac1.sites.pages.cloud.gov/preview/usagov/vote-gov-nvrf-app/bug/vote-732-scroll-top/) both on desktop and on a mobile device (does not act the same if you just reduce the size of your screen on desktop). 
2. Navigate though from and check that as you go to each page you are taken to the top and an see header and language selector.  Keep an eye on after you leave the eligibility page that the next will take you to the top.
> Testing added scroll into view method

- src/components/StateSelection.jsx
[VOTE-748](https://cm-jira.usa.gov/browse/VOTE-748)
Replace h4 with strong tag to fix heading order
> VOTE-765: fix heading order of state selection page

- public/data/en/strings.json
- src/components/FormSections/Delivery.jsx
Ticket: [Vote-858](https://cm-jira.usa.gov/browse/VOTE-858)
Purpose: Adding the main in deadline to the delivery page for the NVRF
Testing:  Log in and fill out form, once you are at the delievery page check that under the address there is the mail in deadline. 
Screen shots below for reference:
> Vote-858: Mail in deadline for delivery page

- src/components/Eligibility.jsx
- src/components/FormSections/Addresses.jsx
- src/components/FormSections/Confirmation.jsx
- src/components/FormSections/Identification.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/components/FormSections/PoliticalParty.jsx
- src/components/HelperFunctions/ValidateField.jsx
- src/components/StateSelection.jsx
> Sprint 54: release to MAIN

- src/components/BackButton.jsx
- src/components/FormSections/Addresses.jsx
- src/components/FormSections/Confirmation.jsx
- src/components/FormSections/Identification.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/components/FormSections/PoliticalParty.jsx
- testing/cypress/e2e/tests/inPerson.cy.js
- testing/cypress/e2e/tests/online.cy.js
- testing/cypress/e2e/tests/verifyErrors.cy.js
- testing/cypress/e2e/tests/workflows.cy.js
- testing/cypress/support/commands.js
Updating target ids with data-test attributes for better maintainability... also updating the `data-testid` that is created by react.  This was recommend at first but adding our own will help with any issues down the line with updates to the elements.
Testing:  Verify that cypress test are now passing within the pipeline
> Post Sprint Cypress Update

- src/components/BackButton.jsx
- src/components/FormSections/Addresses.jsx
- src/components/FormSections/Confirmation.jsx
- src/components/FormSections/Identification.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/components/FormSections/PoliticalParty.jsx
- testing/cypress/e2e/tests/inPerson.cy.js
- testing/cypress/e2e/tests/online.cy.js
- testing/cypress/e2e/tests/verifyErrors.cy.js
- testing/cypress/e2e/tests/workflows.cy.js
- testing/cypress/support/commands.js
CHANGELOG:
VOTE-898 cypress test updates
> Sprint 55: release to MAIN

- src/components/Eligibility.jsx
[VOTE-933](https://cm-jira.usa.gov/browse/VOTE-933)
> VOTE-933: Parse html of deadline dates

- package-lock.json
- package.json
- public/data/en/states.json
- src/components/Eligibility.jsx
- src/components/FormSections/Delivery.jsx
CHANGELOG:
VOTE-1044
VOTE-933 Updated app content for specific deadline dates
VOTE-1060
> Sprint 57: release to MAIN

- public/data/en/navigation.json
Update label and alert text on the confirmation page as defined in the ticket.
https://cm-jira.usa.gov/browse/VOTE-1077
> VOTE-1077 Update label and alert for confirmation page

- public/data/en/navigation.json
- public/data/en/strings.json
Confirm the changes requested in the ticket display correctly on the registration options page.
https://cm-jira.usa.gov/browse/VOTE-1070
> VOTE-1070 Update button text for registration options page

- src/components/FormSections/Confirmation.jsx
- src/components/FormSections/Identification.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/components/MultiStepForm.jsx
[VOTE-1069](https://cm-jira.usa.gov/browse/VOTE-1069)
Changes made to resolve console errors/warnings:
- change all instances of class to className
- move input-parent div up to wrap all identification field possibilities so it isn't trying to be targeted when it doesn't exist yet. The element with id='state-id' now always exists.
- add missing key={0} to legend
> VOTE-1069: Resolve all console log errors

- index.html
- public/theme/assets/styles/nvrf.css
- src/App.jsx
- src/components/Eligibility.jsx
- src/components/FormSections/Addresses.jsx
- src/components/FormSections/Confirmation.jsx
- src/components/FormSections/Delivery.jsx
- src/components/FormSections/Identification.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/components/FormSections/PoliticalParty.jsx
- src/components/MultiStepForm.jsx
- src/components/RegType/InPerson.jsx
- src/components/RegType/NotNeeded.jsx
- src/components/StateSelection.jsx
https://cm-jira.usa.gov/browse/VOTE-847
> VOTE-847 style clean up

- index.html
- public/data/en/strings.json
- public/theme/assets/styles/nvrf.css
- src/App.jsx
- src/components/Eligibility.jsx
- src/components/FormSections/Addresses.jsx
- src/components/FormSections/Confirmation.jsx
- src/components/FormSections/Delivery.jsx
- src/components/FormSections/Identification.jsx
- src/components/FormSections/PersonalInfo.jsx
- src/components/FormSections/PoliticalParty.jsx
- src/components/GenerateFilledPDF.jsx
- src/components/MultiStepForm.jsx
- src/components/RegType/InPerson.jsx
- src/components/RegType/NotNeeded.jsx
- src/components/StateSelection.jsx
**CHANGELOG:**
- VOTE-847: component style and template refinement
- VOTE-868: Update to DOB year font size
- VOTE-1133: Replace hardcoded zip code help text with data from cms
- VOTE-1181: Update edit button component for styling and best practices
> Sprint 59: Release to Main

- src/components/FormSections/PersonalInfo.jsx
[VOTE-1018](https://cm-jira.usa.gov/browse/VOTE-1018)
Changed phone number field's aria-describedby to point to the hint, not the error.
Using accessibility tool (i.e. NVDA), click on the phone number field in Personal Info section, and verify that "(123) 456-7890" is read by the screen reader.
> VOTE-1018: changed phone number input's aria-describedby to the help text

- src/Components/Fields/PreviousStreetAddress.jsx
- src/Views/FormPages/Addresses.jsx
[VOTE-2313](https://cm-jira.usa.gov/browse/VOTE-2313)
implemented FieldContainer for previous street address.
Go to "Address and Location" section.
Toggle on "I have moved since last registered in this state".
Verify that in the previous addr fields, nothing has changed about the street address field, functionality-wise.
> VOTE-2313: implemented FieldContainer for previous street address

- src/Components/Fields/CurrentApartmentNumber.jsx
- src/Components/Fields/PreviousApartmentNumber.jsx
- src/Views/FormPages/Addresses.jsx
[VOTE-2314](https://cm-jira.usa.gov/browse/VOTE-2314)
implemented FieldContainer for previous apartment number (apt #)
Go to "Address and Location" section.
Toggle on "I have moved since last registered in this state".
Verify that in the previous addr fields, nothing has changed about the apartment number (apt #) functionality-wise.
> VOTE-2314: implemented FieldContainer for previous apartment number

- src/Components/Fields/CurrentLastName.jsx
- src/Views/FormPages/PersonalInfo.jsx
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-2290
Implemented the Field Container for the current last name field on the digital form. The field retains its original functionality, including the validation/error message:
After completing the digital form, the content entered into the last name field is displayed correctly on the filled-out PDF.
> VOTE-2290: Field container for current last name

- src/Components/Fields/CurrentSuffix.jsx
- src/Views/FormPages/PersonalInfo.jsx
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-2301
Added a field container for current suffix:
The select field works as intended, and the option that the user selects appears in the final filled PDF.
To test, complete the online form and choose a suffix on the Personal Information page. Ensure that the selection appears on the Confirm your Information page and the final PDF.
> VOTE-2301: Field Container for current suffix

- src/Components/Fields/PoliticalPartyInput.jsx
- src/Views/FormPages/PoliticalParty.jsx
Ticket - [Vote-2327](https://cm-jira.usa.gov/browse/VOTE-2327)
Description - adding filed container to political party 
Testing 
1. start up local 
2. work through from until you get to the political party page and verify that there are no regressions 
3. input test such as `pizza party` and progress to the next page and verify that on the confirm page the text is present and check that the PDF download has the correct text
> Vote-2327: Field Container - Political Party

- src/Components/FieldComponents/TextInputField.jsx
- src/Components/FieldContainer.jsx
- src/Components/Fields/CurrentPhoneNumber.jsx
- src/Utils/ValidateField.jsx
- src/Views/FormPages/PersonalInfo.jsx
[VOTE-2303](https://cm-jira.usa.gov/browse/VOTE-2303)
implemented FieldContainer for current phone number field.
Fixed 'check value length' part of the checkForErrors() function.
Go to "Personal Information" section.
Verify that in the current phone number field:
1. Only numbers are allowed to be typed.
2. Must be 10 digits, else error shows up
3. If error, cannot proceed on
4. Phone number shows up on final form
> VOTE-2303: implemented FieldContainer for current phone number field

- src/Components/FieldComponents/TextInputField.jsx
- src/Components/Fields/PreviousCity.jsx
- src/Views/FormPages/Addresses.jsx
[VOTE-2315](https://cm-jira.usa.gov/browse/VOTE-2315)
implemented FieldContainer for previous city field.
Go to "Address and Location" section
Select "I have moved since I last registered in this state."
For the city field in previous address section, verify that:
1. Only alphabets can be typed (no numbers)
2. If required, and nothing is typed, cannot proceed on
3. The typed city shows up in the final form
> VOTE-2315: implemented FieldContainer for previous city

- src/Components/Fields/PreviousLastName.jsx
- src/Views/FormPages/PersonalInfo.jsx
[VOTE-2307](https://cm-jira.usa.gov/browse/VOTE-2307)
implemented FieldContainer for previous lastname field.
Go to "Personal Information" section
Select "I have legally changed my name since I last registered in this state."
For the lastname field in previous name section, verify that:
1. Error is shown if attempted to proceed while empty.
2. The lastname value shows up in the final form.
> VOTE-2307: implemented FieldContainer for previous lastname

- src/Components/Fields/PreviousTitle.jsx
- src/Views/FormPages/PersonalInfo.jsx
[VOTE-2304](https://cm-jira.usa.gov/browse/VOTE-2304)
implemented FieldContainer for previous title select field.
Go to "Personal Information" section
Select "I have legally changed my name since I last registered in this state."
For the title select in previous name section, verify that:
1. The title select value is changeable.
2. The title state value shows up in the final form.
> VOTE-2304: implemented FieldContainer for previous Title select

- src/Components/Fields/PreviousFirstName.jsx
- src/Views/FormPages/PersonalInfo.jsx
[VOTE-2305](https://cm-jira.usa.gov/browse/VOTE-2305)
implemented FieldContainer for previous firstname field.
Go to "Personal Information" section
Select "I have legally changed my name since I last registered in this state."
For the firstname field in previous name section, verify that:
1. Error is shown if attempted to proceed while empty.
2. The firstname value shows up in the final form.
> VOTE-2305: implemented FieldContainer for previous firstname 

- src/Components/Fields/PreviousMiddleName.jsx
- src/Views/FormPages/PersonalInfo.jsx
[VOTE-2306](https://cm-jira.usa.gov/browse/VOTE-2306)
implemented FieldContainer for previous middlename field.
Go to "Personal Information" section
Select "I have legally changed my name since I last registered in this state."
For the middlename field in previous name section, verify that:
1. The middlename value shows up in the final form.
> VOTE-2306: implemented FieldContainer for previous middlename 

- src/Components/Fields/PreviousAddressState.jsx
- src/Views/FormPages/Addresses.jsx
[VOTE-2316](https://cm-jira.usa.gov/browse/VOTE-2316)
implemented FieldContainer for previous state select field.
Go to "Address and Location" section
Select "I have moved since I last registered in this state."
For the state select in previous address section, verify that:
1. The select value is changeable.
2. The state value shows up in the final form.
> VOTE-2316: implemented FieldContainer for previous address state select

- src/Components/Fields/StateIDNum.jsx
- src/Views/FormPages/Identification.jsx
1. Load up the local site.
2. Navigate through form to "Identification"
3. Select State non-driver ID
4. Test validation still works as expected
5. Test confirm page includes data as expected
[VOTE-2325](https://cm-jira.usa.gov/browse/VOTE-2325)
> VOTE-2325: field container for state non driver ID

- src/Components/Fields/SSNPartial.jsx
- src/Views/FormPages/Identification.jsx
[VOTE-2326](https://cm-jira.usa.gov/browse/VOTE-2326)
> VOTE-2326: implement container for partial SSN field

- src/Components/FieldComponents/TextInputField.jsx
- src/Components/Fields/MailingCity.jsx
- src/Views/FormPages/Addresses.jsx
[VOTE-2320](https://cm-jira.usa.gov/browse/VOTE-2320)
implemented FieldContainer for mailing city field.
Go to "Address and Location" section
Select "I get my mail at a different address from the one above."
For the city field in mailing address section, verify that:
1. Only alphabets can be typed (no numbers)
2. If required, and nothing is typed, cannot proceed on
3. The typed city shows up in the final form
> VOTE-2320: implemented FieldContainer for mailing city

- src/Components/FieldComponents/DateFields.jsx
- src/Components/Fields/CurrentDateOfBirth.jsx
- src/Utils/ValidateField.jsx
- src/Views/FormPages/PersonalInfo.jsx
- src/Views/MultiStepForm.jsx
[VOTE-2302](https://cm-jira.usa.gov/browse/VOTE-2302)
implemented FieldContainer for current DOB field.
Go to "Personal Information" section.
Verify that in the current DOB fields:
1. Month can only be >=1 and <= 12
2. Day can only be >= 1 and <= 31
3. Year can only start with 19 or 20
4. Calculated age from the date is at least 16.
5. If any of the above aren't satisfied, error is shown and cannot proceed on.
> VOTE-2302: implemented FieldContainer for current DOB

- src/Components/FieldComponents/TextInputField.jsx
- src/Components/Fields/CurrentCity.jsx
- src/Components/Fields/CurrentPhoneNumber.jsx
- src/Components/Fields/CurrentZipCode.jsx
- src/Components/Fields/PreviousCity.jsx
- src/Components/Fields/SSNPartial.jsx
- src/Views/FormPages/Identification.jsx
[VOTE-2326](https://cm-jira.usa.gov/browse/VOTE-2326)
original PR: https://github.com/usagov/vote-gov-nvrf-app/pull/267
This PR makes an update to handle the regression issue so now the field should only accept letters and throws an error if less than 4 numbers are entered. I also made minor updates to keep all the variables consistent and add default values.
> VOTE-2326: Fix SSN field regression

- src/Components/Fields/CurrentApartmentNumber.jsx
- src/Components/Fields/CurrentMiddleName.jsx
- src/Components/Fields/CurrentSuffix.jsx
- src/Components/Fields/CurrentTitle.jsx
- src/Components/Fields/PreviousApartmentNumber.jsx
- src/Components/Fields/PreviousMiddleName.jsx
- src/Components/Fields/PreviousTitle.jsx
[VOTE-2577](https://cm-jira.usa.gov/browse/VOTE-2577)
Passed 'required' as string for all FieldContainers.
Go to `Personal Information` section.
Click on "I have legally changed my name since I last registered in this state." Checkbox.
Verify that in the browser console, there are no warnings regarding required attribute being NaN.
Go to `Address and Location` section.
Click on "I have moved since I last registered in this state."
Click on "I get my mail at a different address from the one above."
Verify that in the browser console, there are no warnings regarding required attribute being NaN.
> VOTE-2577: Passed 'required' as string for all FieldContainers

- public/theme/assets/styles/nvrf.css
- src/Components/ProgressBar.jsx
[VOTE-2567](https://cm-jira.usa.gov/browse/VOTE-2567)
Disallow going back after confirmation step in Multistep stage
Reach the "Confirm your information" Step after filling all the necessary fields out.
Verify that you can still go back to any of the 4 steps before this step.
Now click the "The information I have provided is true to the best of my knowledge under penalty of perjury" selectbox, then proceed to "Print your completed form".
Now verify that you CANNOT go back to any of the 5 steps before this step.
> VOTE-2567: Disallow going back after confirmation step in Multistep stage

- src/Components/Fields/RaceEthnicity.jsx
- src/Views/FormPages/PersonalInfo.jsx
- testing/cypress/support/commands.js
Ticket -> [Vote-2579](https://cm-jira.usa.gov/browse/VOTE-2579)
Purpose -> Move Race/Ethnicity to field wrapper component
Testing steps:
Visit [preview link](https://federalist-aef5b597-8e18-44b6-aeba-3fc3f17cdac1.sites.pages.cloud.gov/preview/usagov/vote-gov-nvrf-app/feature/vote-2579-ethnicity-field-container/) and progress through the from by selecting either registration option and select a Race/Ethnicity option
Verify that user can still select the option and complete the form and that the info is saved on the confirm page and on the downloaded nrvf doc
> Vote-2579: Race/Ethnicity to field container

- src/Components/Fields/PreviousSiffix.jsx
- src/Components/Fields/PreviousSuffix.jsx
- src/Views/FormPages/PersonalInfo.jsx
Ticket -> [Vote-2580](https://cm-jira.usa.gov/browse/VOTE-2580)
Purpose -> Move Previous Suffix to field wrapper component 
Testing steps:
1. Visit [preview link]() and progress through the from by selecting `Update Registration status` and selection the option for name change
2. Verify that user can still select the suffix option and complete the form and that the info is saved on the confirm page and on the downloaded nrvf doc
> Vote-2580: Previous Suffix field wrapper

- index.html
- src/App.jsx
https://cm-jira.usa.gov/browse/VOTE-2729
1. Remove the `data-privacyPath` attribute from index.html and make sure the link is removed.
2. Update the `data-privacyPath` attribute from index.html and make sure the link point to the new url.
> VOTE-2729 Add dynamic privacy link to app

- index.html
- src/Views/FormPages/Delivery.jsx
- testing/cypress/e2e/tests/inPerson.cy.js
- testing/cypress/e2e/tests/online.cy.js
[VOTE-2117](https://cm-jira.usa.gov/browse/VOTE-2117)
Description:
1. Added data layer events to both PDF buttons
2. Adjusted the PDF button tests
Test:
1. Go through the form to the Delivery page
2. Test the "new tab" PDF button and confirm the PDF generates
3. Test the "download" PDF button and confirm the PDF generates
NOTE: We will not be testing functionality of GA4 with our code until all analytics tickets are completed. There is a separate ticket to confirm with the analytics team.
> VOTE-2117: Analytics - Generate PDF Buttons

- src/Components/FieldComponents/DateFields.jsx
Ticket: https://cm-jira.usa.gov/browse/VOTE-2767
We are removing general field validation for DOB age in favor of state instructions.
Test the following cases for the DOB field
1. 04/10/1998 - pass
2. 12/12/2010 - pass
3. 08/31/2100 - fail
> VOTE-2767 Remove DOB age validation

- package-lock.json
- package.json
Ticket: [Vote-2867](https://cm-jira.usa.gov/browse/VOTE-2867)
Description:  Updates from Dependabot will close out -> https://github.com/usagov/vote-gov-nvrf-app/pull/310 and https://github.com/usagov/vote-gov-nvrf-app/pull/312
Testing: 
1. run `npm i` and start up app
2. fill out form and confirm no issues and no issues with the pdf options
> Vote-2867: Dependabot updates

- src/Components/FieldComponents/SelectField.jsx
Ticket:
[VOTE-2848](https://cm-jira.usa.gov/browse/VOTE-2848)
Description:
Adds the validation check for a value on the select lists onBlur.
Testing:
1. Go through the complete form testing each *required select list by
2. Tabbing over or clicking in and out of the box before adding a value, confirm error message appears
3. Add a value then click or tab out again and confirm error message disappears
> VOTE-2848: Add onBlur validation to SelectField

- package-lock.json
- package.json
Ticket: [Vote-135](https://cm-jira.usa.gov/browse/VOTE-3135)
Description:  Updating NPM packages that were outdated 
- a follow up ticket as been made for updating react but needed package for USWDS react will need to be updated for this new version. 
Testing:
1. run `npm i` and `npm run build` and ensure that builds with no errors 
2. start up app and fill out form and check for any major regressions 
3. cd into `testing` and run `npm run cy:test`
> Vote-135: NPM Audit

- .circleci/config.yml
- src/App.jsx
- src/Views/FormPages/Confirmation.jsx
- testing/cypress/e2e/accessibility/axe.cy.js
- testing/package-lock.json
- testing/package.json
Ticket - [Vote-2897](https://cm-jira.usa.gov/browse/VOTE-2897)
Purpose - This pr will add accessibility test to the NVRF form and added to the pipeline to run on each PR.  Based on chatting with others and looking at the set up for component tests i felt this would be best to fill out the form with text to help recreate a user and give the test a more real word set up. 
There were 2 minor errors that have also been addressed. 
Testing - 
1. check the Circle ci build and check that test is passing 
2. start local and spilt terminal and then cd into `testing` and run `npm i` and also run `npm run cy:axe` and verify that test is passing
> Vote-2897: Adding Accessibility Test

- src/App.jsx
- src/Components/ProgressBar.jsx
- src/Views/FormPages/Confirmation.jsx
https://cm-jira.usa.gov/browse/VOTE-3393
**Testing steps:**
1. Start the app locally `npm start`
2. Confirm the progress bar `aria-live` message updates for each step to the appropiate label (example: "Step five of six: Confirm your information") also test this in Spanish.  Note: The step label will be translated but not the "Step five of six:" part because that was never translated.
3. On the confirmation page inspect the edit buttons and make sure the `title` attribute value matches what is on production. Spanish will also be in English until this is translated.
> VOTE-3393: Replace hardcoded screen reader text with dynamic API values

- src/Views/FormPages/Confirmation.jsx
- src/VoteError.css
https://cm-jira.usa.gov/browse/VOTE-2861
Visit http://localhost:5173/ and complete the form to the Confirmation page and confirm the edit buttons look like buttons now.
> VOTE-2861: Update edit button format

- README.md
https://cm-jira.usa.gov/browse/VOTE-3401
Update readme with more robust information.
> VOTE-3401 Update readme

- src/Views/Eligibility.jsx
- src/Views/FormPages/Addresses.jsx
- src/Views/FormPages/Confirmation.jsx
- src/Views/FormPages/Identification.jsx
- src/Views/FormPages/PersonalInfo.jsx
- testing/cypress/e2e/tests/nvrfForm.cy.js
- testing/cypress/e2e/tests/verifyErrors.cy.js
- testing/cypress/support/commands.js
- testing/cypress/support/pageObjects.js
https://cm-jira.usa.gov/browse/VOTE-3371
Test steps
1. Go through the form (change registration path) and confirm each single checkbox has a field set by inspecting in dev tools
2. Confirm the screenreader reads out the checkboxes and labels correctly.
> VOTE-3371 Add fieldsets to single checkboxes

- src/Components/Footer.jsx
- src/Context/DataProvider.jsx
- src/Views/PathSelection.jsx
https://cm-jira.usa.gov/browse/VOTE-3517
Description:
We are now fetching card data and footer data from the strings endpoint.
Testing:
Visit the preview link and confirmt the two path cards are displaying content on the next step of the app. The footer content does not display in the preview but will display when the CMS changes have been deployed.
> VOTE-3517 update nvrf card and footer data dependencies
