usagov/vote-gov-nvrf-app

- src/components/FormSections/ValidateField.jsx
[VOTE-248](https://cm-jira.usa.gov/browse/VOTE-248)
Test by using the City input under Personal Information section of the form. It should only allow spaces and alphabetical letters.
> VOTE-248: allow spaces in City and Party inputs

- src/components/FormSections/Addresses.jsx
- src/components/FormSections/PersonalInfo.jsx
[VOTE-279](https://cm-jira.usa.gov/browse/VOTE-279)
Examples for field inputs should use consistent formatting
> VOTE-279: update the markup of input field examples

- src/components/FormSections/Confirmation.jsx
Jira: https://cm-jira.usa.gov/browse/VOTE-339
Test steps:
1. Fill out the form, the first time filling out the date id fields, and stop on the confirm page.
2. Confirm the id dates have the format of month/day/year
3. Click "edit" next to Identification. Clear the dates, and select "none" from the drop down
4. Go back to the confirm page and verify the id date fields show up empty (without any slashes "//")
> VOTE-339 Hide the // in id date fields when empty

- src/components/FormSections/Confirmation.jsx
- src/components/MultiStepForm.jsx
[VOTE-529](https://cm-jira.usa.gov/browse/VOTE-529)
To test fill out the different address types in different combinations using the checkboxes to hide/show fields and confirm they are displaying correctly on the confirmation page. example: previous + current, previous + mailing, mailing, current, etc..
> Bugfix/vote 549/data fields reset

- src/components/FormSections/Confirmation.jsx
- src/components/GenerateFilledPDF.jsx
Test by filling out any address data OTHER THAN current address. Confirm the selected state is not included under "current address" section of confirm page or filled in on the pdf. Test that it does show when current address is filled out.
> VOTE-575: Remove default state from current address section of confirm/pdf 

- src/components/FormSections/PersonalInfo.jsx
Ticket - [Vote-571](https://cm-jira.usa.gov/browse/VOTE-571)
Purpose - Adding `0` in the accepted numbers that can be accepted in the date of birth fields 
Testing:
1. Visit [preview link]() and select `Alaska` and navigate to the Personal Information Page and fill out all the fields. 
2. For date of birth add `10, 10, 2000` and ensure that you are able to move forward
> Vote-571: Fix Date of Birth to accept `10`

- src/components/FormSections/PersonalInfo.jsx
Ticket: https://cm-jira.usa.gov/browse/VOTE-633
Description: Fixed the required symbol. logic for the race/ethnic group field, so the asterisk displays instead of a '0' character.
Testing steps:
1. Select "Georgia" and confirm the required symbol shows in the field label.
2. Select "Florida" and confrim the required symbol does no show in the field label.
3. Select "Alaska" and confirm the race field is hidden.
> VOTE-633 Fix race field label

- public/data/en/navigation.json
- src/components/Eligibility.jsx
- src/components/RegType/ByMail.jsx
Purpose: This Pr will update the 'start' button to have the correct text of `I want to use vote.gov’s mail-in form` instead of the old `Start your online registration on vote.gov`
Ticket: [Vote-673](https://cm-jira.usa.gov/browse/VOTE-673)
Testing:
1. Visit [preview link](https://federalist-aef5b597-8e18-44b6-aeba-3fc3f17cdac1.sites.pages.cloud.gov/preview/usagov/vote-gov-nvrf-app/bug/vote-673-state-btn-udpate/) and visit the following states `Arkansas`, `Maine`, `Mississippi`, `Montana`, `New Hampshire`, `Oklahoma`, `South Dakota`, `Texas` and `Wyoming`
2. Check that the 'start' button on the first 2 pages have the correct text of `I want to use vote.gov’s mail-in form` 
See screen shot below for OLD reference
> Vote:673 - Start Button Text Update

- src/components/FormSections/PersonalInfo.jsx
- src/components/MultiStepForm.jsx
Purpose:  This PR will update the checkbox on `name change` on Personal Info page to stay selected when the user leaves the page. 
Ticket: [Vote-685](https://cm-jira.usa.gov/browse/VOTE-685)
Testing:
1. Check [preview link]() and select a state
2. Make your way to the personal info page from the `change registration` option and select the name change option 
3. Move to next page and then go back to personal info page and ensure that checkbox is still selected
> Vote-685: Update to checkbox on personal info page 

- src/components/FormSections/PoliticalParty.jsx
Purpose: This PR will move the generic political party instructions to be out of the alert field and under the text box.. this text has also been updated in the CMS and will be new as well. 
Ticket: [Vote-729](https://cm-jira.usa.gov/browse/VOTE-729)
Testing:
- select a state and navigate to the political party... the expected result is that there is only one alert and then text below the text field 
Below is from Alabama 
Before:
After:
> Vote-729: Update to political page instructions

- src/components/GenerateFilledPDF.jsx
This reverts VOTE-618
https://cm-jira.usa.gov/browse/VOTE-618
Confirm that the Utah identification special case is removed.
> Remove the special id case for Utah

- src/components/FormSections/Identification.jsx
- src/components/MultiStepForm.jsx
Ticket: [Vote-763](https://cm-jira.usa.gov/browse/VOTE-763)
Purpose: This Pr will fix the error where multiple inputs were rendering on the confirmation page. 
Testing:
1. Visit [preview link](https://federalist-aef5b597-8e18-44b6-aeba-3fc3f17cdac1.sites.pages.cloud.gov/preview/usagov/vote-gov-nvrf-app/bug/vote-763-id-page/) and select a state and navigate to the id page
2. Select each option and ensure that you can see that option on the conformation page. Once you have done that go back and select a new options with new numbers and check that the correct number is present and there is only one and not multiple.
> Vote-763: ID page fix

- public/data/en/strings.json
- src/components/StateSelection.jsx
- src/components/StateSelector.jsx
There was an extra select in the stings file that was not rendering the right text for state selection.
Here are screen shots to show the issue and fix
> BUG: Multiple Selects in String Json File 

- src/components/RegType/Online.jsx
Hot fix to address string after state selection to read "visit states on line form"
To text -> visit preview link and check that Alaska, Guam, Colorado and California read "visit states online form" in the first button after state selection
> HOTFIX: Updated "states online form" button string

- .circleci/config.yml
VOTE-822
Changes to the NVRF PDF Upload job:
1. Change git clone to an git ssh clone command
2. Override default shell command in PR step
3. Override pipeline fail in PR command. Empty PR (resulting from no changes to the PDF) will not result in failed job
> VOTE-822 update circlci configuration for pulling the latest EAC PDF

- src/components/RegType/OnlineNoNvrf.jsx
- src/components/RegType/OnlineNoStateMail.jsx
- src/components/RegType/OnlineOnly.jsx
Fix a regression in the registration button labels. [VOTE-1111](https://cm-jira.usa.gov/browse/VOTE-1111)
Visit each of these state pages and confirm button labels are correct according to the content linked in the ticket.
1. Alaska (online)
2. Maine (all mail-in)
3. Guam (online, no nvrf, no state mail)
4. Wisconsin (online, no nvrf)
5. New Hampshire (mail, no nvrf)
6. North Dakota (no registration)
7. American Samoa (in person only)
8. Wyoming (state specific template)
> VOTE-1111 Fix reg button labels

- src/components/GenerateFilledPDF.jsx
Ticket: [Vote-868](https://cm-jira.usa.gov/browse/VOTE-868)
Purpose:  Adjust text size for DOB field font sizes, currently the year for DOB is only 2 characters and not 4 so the year is getting cut off... now this will allow the user to have the full year showing.
Testing: Fill out form and check that the full year is showing for the DOB on the pdf form
> Vote-868: Update to DOB field font size

- public/data/en/strings.json
- src/components/FormSections/Addresses.jsx
Ticket: [VOTE-1133](https://cm-jira.usa.gov/browse/VOTE-1133)
Description: Replace hardcoded and duplicate help text for the mail zip code with the data from the CMS.
Test steps:
1. Start the form on the "Begin new registration" path for Alaska
2. On the address page, confirm that all zip code fields have the correct help text according to the ticket. (Current address, previous address, alt mail address)
> VOTE-1133 Replace hardcoded zip code help text with data from cms

- public/data/en/strings.json
- src/components/StateSelection.jsx
Added an aria-label for the `StateSelection` component that appears on the first page of the NVRF app. The aria-label message is written in `strings.json`.
> VOTE-750: aria-label for State Selection component

- public/data/en/fields.json
- src/components/FormSections/PoliticalParty.jsx
Moved the help text for the political party selection field from below the text input box to above.
**Before**:
*it seems like this screenshot was from an older version, and more content has been added to the help text since then.
**After**:
The text type was also changed from `"instructions"` to `"help_text"` in the JSON, and a `<span>` tag was used instead of `dangerouslySetInnerHTML`. Other text fields in the app appear to have help text added via `<span>` tags, while instructions are added via `dangerouslySetInnerHTML`, so I made sure that this was consistent.
*minor note: some of the text content in the help text is somewhat redundant with the text in the blue info box above
> VOTE-1022: Move political party help text above text field

- public/data/en/fields.json
- src/components/FormSections/Addresses.jsx
Added instructions for the optional checkbox(es) at the top of the "Address and location" page. If the user is updating a current registration, two checkboxes will appear on the page, like below:
The added instructions above the checkboxes reflect that there are two checkboxes.
If the user is creating a new registration, only one checkbox appears on the page, like below:
The instructions also reflect this.
> VOTE 2030: Adding instructions for checkboxes on address page

- src/components/FormSections/PersonalInfo.jsx
[VOTE-668](https://cm-jira.usa.gov/browse/VOTE-668)
Uncommented age verification to verify the user is between 17 and 110.
p.s.
I'm not sure if enabling age verification was in the scope of this ticket, but entering future date was already not allowed as the regex is '200\{1}'
1. Go to Personal Information section.
2. In the DOB fields, verify you can't enter dates that make you younger than 16 and older than 120.
> VOTE-668: DOB disallow future date

- public/theme/assets/styles/nvrf.css
- src/components/MultiStepForm.jsx
- src/components/ProgressBar.jsx
Added functionality to make completed form segments (navy blue color) clickable, where clicking on a completed segment will allow the user to jump back to that specific section of the form. When hovering over the segment for a completed section, the mouse pointer indicates that the section is clickable, but does not do so for the current section (blue) and future sections (gray). Clicking on the current section or a future section does not do anything (preventing the user from skipping ahead).
Demo:
> VOTE-1979: Make completed form segments clickable

- src/components/StateSelection.jsx
Added the `select` role to the state/territory selector element, and removed the `aria-invalid` attribute, which is not allowed on elements where role="select".
> VOTE-2226: Add role to state/territory selector

- public/data/en/fields.json
- src/components/FormSections/PoliticalParty.jsx
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-2284
Reverted the political party selection instructions in fields.json to its original state (text content surrounded by `<p>` tags). In order to prevent the `<p>` tags from being visible to the user, the political party instructions are added using `dangerouslySetInnerHTML` (following how other instructions content from fields.json is added to the page). The text appears as follows:
> VOTE-2284: Revert party instructions content

- src/Components/Fields/CurrentMiddleName.jsx
- src/Views/FormPages/PersonalInfo.jsx
Added Field Container for the current middle name field. The field works as intended and the text entered appears in the filled PDF.
In fields.json, the current middle name field has help text ("If you do not have a middle name, leave this field blank.") that is not currently being used, but does appear now that a Field Container is being used. If we don't want this help text to appear, I think we could either delete it via CMS or I could set help_text to false in the Field Container (but leave the unused text in the JSON file).
If we want to keep the text, it appears that the alignment of the text fields becomes somewhat misaligned with the new help text. See below:
I can adjust the CSS to re-align the text boxes if we do want to keep the text. See below:
(this does create some extra …
> VOTE-2289: Field Container for middle name

- src/Components/FieldComponents/SelectField.jsx
- src/Components/FieldContainer.jsx
- src/Components/Fields/CurrentTitle.jsx
- src/Views/FormPages/PersonalInfo.jsx
Added a field container for the current title Select element. The element functions as expected, and the value chosen by the user appears in the filled PDF.
Note: the original default value ("-Select-") is replaced by a blank option as the default value. I think that "-Select-" would need to be added as an option in `fields.json`.
> VOTE-2287: Field Container for current title

- src/Components/Fields/MailingStreetAddress.jsx
- src/Views/FormPages/Addresses.jsx
[VOTE-2318](https://cm-jira.usa.gov/browse/VOTE-2318)
implemented FieldContainer for mailing street address.
Go to "Address and Location" section.
Toggle on "I get my mail at a different address from the one above".
Verify that in the mailing addr fields, nothing has changed about the street address field, functionality-wise.
> VOTE-2318: implemented FieldContainer for mailing street address

- src/Views/FormPages/Addresses.jsx
- src/Views/FormPages/PersonalInfo.jsx
[VOTE-2489](https://cm-jira.usa.gov/browse/VOTE-2489)
Originally DOB was the only field using the "hint" span. Now adding a hint to just one field on other rows causes the fields to not align together. This PR adds flex-align-end to all form rows the same way we did with the rows that have the date fieldsets. The fields should not shift now when one or more hints are added.
Before:
Now:
> VOTE-2489: Flex align all grid rows

- public/data/en/fields.json
- src/Views/FormPages/Addresses.jsx
Added instruction text for address checkboxes.
When the user is updating their registration, the checkboxes and instructions appear like this:
When the user is creating a new registration, the checkbox and instructions appear like this:
To test, begin the digital form filler for updating a registration and continue to the 'Address and location' page. Ensure that the text appears as it does in the above screenshot, and that both checkboxes function correctly (the page should respond when either/both checkboxes are checked).
Then, go back and begin a new registration, continue to the 'Address and location' page, and ensure that the text matches the second screenshot above.
> VOTE-2030: New instructions for address checkboxes

- src/Components/Fields/DriversLicenseNumber.jsx
- src/Views/FormPages/Identification.jsx
Added a field container for driver's license number. The field maintains intended functionality, and the number entered by the user appears in the filled PDF.
To test, complete the online registration form, and select 'State driver's license number' on the Identification page. Enter a number into the text field, and check that the number entered appears in the final PDF. If the field is left blank, an error message should display:
> VOTE-2323: Field Container for driver's license

- src/Components/FieldComponents/TextInputField.jsx
- src/Components/Fields/MailingZipCode.jsx
- src/Views/FormPages/Addresses.jsx
[VOTE-2322](https://cm-jira.usa.gov/browse/VOTE-2322)
implemented FieldContainer for mailing zipcode field.
Go to "Address and Location" section
Select "I get my mail at a different address from the one above."
For the zipcode field in mailing address section, verify that:
1. Only numbers can be typed
2. Only 5 digits can be typed
3. If required, and nothing is typed, cannot proceed on
4. The typed zipcode shows up in the final form
> VOTE-2322: implemented FieldContainer for mailing zipcode

- public/theme/assets/styles/nvrf.css
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-776
Currently, when the screen width is <= 640px, the text on the progress bar will be hidden and a new "_ of 6: ..." label will appear. This fix hides the progress bar to avoid redundancy and prevent the user from accidentally clicking/tapping one of the previous segments, which would navigate them back to that segment.
Before:
After:
To test this, open the NVRF app and navigate to the online form. Using the "responsive" dimensions on chrome dev tools, resize the width of the screen and verify that, at <=640px, the progress bar disappears and the new "_ of 6: ..." label appears.
> VOTE-776: Hide the step indicator progress bar on small screens

- public/theme/assets/styles/nvrf.css
- src/Components/ProgressBar.jsx
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-2414
Added hover/focus state styling for previous steps in the step indicator to show that they are clickable/interactable. When hovering or focusing on a previous step, the text should be underlined and shift to a blue color, while the background of that step shifts to a light blue color. See below example, where the mouse is hovering over the 'Address and location' step.
To test, open the form filler and check that no hover/focus styles are present on the current or future step segments. Then, complete at least one step of the form, and then check the hover/focus styles on the completed step segment. The styling shown above should appear when the segment is under the mouse, or when the user uses 'tab' to focus on the completed segment …
> VOTE-2414: Hover state styling for previous steps

- src/Components/FieldComponents/DateFields.jsx
- src/Components/Fields/CurrentDateOfBirth.jsx
- src/Components/FieldsetContainer.jsx
- src/Views/FormPages/PersonalInfo.jsx
Moved the logic for the checkDateValues validation function from PersonalInfo.jsx to DateFields.jsx, and removed unneeded references to checkDateValues in CurrentDateOfBirth.jsx and FieldsetContainer.jsx.
To test, open the NVRF Personal Info page, and enter values into the date of birth field to ensure that the validation is still working correctly. See below for examples:
> VOTE-2578: Migrate checkDateValues to DateFields

- src/Views/Eligibility.jsx
Added the button to go back to state registration options from the Eligibility Requirements page. The button appears here:
It doesn't currently do anything, since it will navigate back to a vote.gov page (once NVRF and vote.gov are integrated). Clicking the button just reloads the current page.
To test, open the NVRF app and ensure the button appears in the correct place on the initial page. Click the button to ensure that it doesn't cause any issues.
> VOTE-2590: Add button to go back to state registration options

- src/Components/FieldContainer.jsx
This fix removes empty spans for fields that do not have a hint and/or do not have an error message (the latter meaning that the field is not required). Previously, fields that did not have a hint would have an empty hint span, such as the First name field below:
This fix removes the unused hint span:
Previously, fields that were not required (and did not have error text) would have an empty span for an error message, as seen with the Middle name field below:
This fix removes the unused span:
To test, open the NVRF form and inspect each of the fields. Fields that do not have grey hint text should not have the hint span, and fields that are not required should not have the error message span.
> VOTE-2543: Remove unused spans in FieldContainers

- src/Components/Fields/CurrentSuffix.jsx
- src/Components/Fields/CurrentTitle.jsx
- src/Components/Fields/PreviousSuffix.jsx
- src/Components/Fields/PreviousTitle.jsx
- src/Components/Fields/RaceEthnicity.jsx
Ticket: [Vote-2703](https://cm-jira.usa.gov/browse/VOTE-2703)
Description:  Updated the value prop to help the data be saved once the user left the page and then returned 
Testing: 
1. Start up local and progress through form and select the update registration path
2. Fill out the options for current and prev suffix, current and prev title and race
3. Progress to the next page and return back to personal info... should verify that the same options are being displayed 
4. Complete form and use the edit button for personal info and verity that the same info is displaying
5. Verify that info is saved to the pdf form as well
> Vote-2703: Bug -> update select fields on personal info page

- src/Components/Fields/SSNFull.jsx
- src/Views/FormPages/Identification.jsx
[VOTE-2581](https://cm-jira.usa.gov/browse/VOTE-2581)
Implements container field to the full social security number field.
Testing:
1. in index.html you will need to change `data-stateId="al"` to `data-stateId="va"` or another state that uses the full ssn field
2. Test the field making sure error handling works as expected and the data is saved on the confirm info page.
3. Edit the input and confirm the data is updated on confirm page
> VOTE-2581: Implement container field for SSNFull

- .circleci/config.yml
ticket: [Vote-2278](https://cm-jira.usa.gov/browse/VOTE-2728)
Purpose: To Disable the NVRF PDF job in the pipeline 
Testing: Verify that the job is commented out and check that the Cypress tests are still passing
> Vote-2278: Disable NVRF PDF Pipeline Job

- src/Components/Fields/StateIDNum.jsx
https://cm-jira.usa.gov/browse/VOTE-2790
Description:
The State Non-Driver's ID field was pointing to the Driver's License field data, resulting in an incorrect field label.
Both fields point to the same PDF field, so there are no changes there.
Testing:
1. Open the form locally and go through the form until the Identification section
2. Select "State Non-Driver ID" and confirm the label above the input box is correct
3. Input data and more forward to the confirmation page
4. Click "edit" next to the Identification field on the confirm page and go back to the ID field
5. Edit the "State Non-Driver ID"
6. Confirm the data changed on the confirmation page
7. Confirm the data is correctly mapped to the PDF field (both the "new tab" and "download" options)
> VOTE-2790 Fix the uuid in the State Non-Driver Identification field

- src/App.jsx
- src/Utils/GenerateFilledPDF_en.jsx
- src/Utils/GenerateFilledPDF_es.jsx
- src/Utils/pdfLoader.jsx
Ticket: [Vote-2725](https://cm-jira.usa.gov/browse/VOTE-2725)
Description:  This PR will load the NVRF PDF when the app mounts to ensure that the file is able to be accessed by the user 
Solution:  
1. Created a new file that takes the upload script and added to the utils folder 
2. Added a `useEffect` to the app.jsx file and added the probs to the multistep form component so that it would be loaded when the app starts up
3. Updated the generatepdf files to pull the data from the spirit file to still have access 
Testing: 
1. Loading up the app and complete the form
2. Verify that you can both download and open the pdf in a new tab and that info is till saving as expected
> Vote-2725: Load PDF on App Load

- src/Utils/GenerateFilledPDF_en.jsx
- src/Utils/GenerateFilledPDF_es.jsx
**Ticket:** [Vote-2809](https://cm-jira.usa.gov/browse/VOTE-2809)
**Description:**  This PR will add a fall back to the generate PDF function to still render a full version of the PDF if in the CMS the page numbers are not saved.  This will allow for a user to still have access to the PDF and their saved data. 
This update was made to both English and Spanish to help catch any issue that might happened with the NVRF page setting.
**Solution:**  Adding a conditional statement to the part of the function that removes the unneeded pages. 
**Testing:** 
1. Pull down local and start up app 
2. Open the `states.json` file under `nvrf/assets` folder.  
3. Do a search for `"nvrf_pages_list":"1,2,3,4,7"` when you find it make sure it is for alabama and clear out the number so it should look like …
> Vote-2809: Add Fallback if NVRF pages is left empty

- data/es/strings.json
- data/strings.json
- src/Views/Eligibility.jsx
- src/Views/FormPages/Delivery.jsx
- src/Views/MultiStepForm.jsx
- src/Views/PathSelection.jsx
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-2113
Description: Add dataLayer event to the Next Button that pushes the current page (just completed step) to GTM.
Test steps:
1. Open the form locally
2. Fill out the form until the Delivery page. Use the update path. 
3. Click the "Open in a new tab" PDF button.
4. Open the console and type 'dataLayer'. Press Enter.
5. Verify the following values are present in the dataLayer. The indexes do not matter, but they should be in this order. You can ignore the other click events done by default by GTM.
NVRF_page_title: 'Before you get started page', event: 'NVRF_STEP_SUBMIT'
NVRF_path: 'update_registration_path', NVRF_page_title: 'Path Selection page', event: 'NVRF_STEP_SUBMIT'
NVRF_page_title: 'Personal information page', event: …
> VOTE-2113: Analytics for the next buttons

- public/es/nvrf/data/strings.json
- public/nvrf/data/strings.json
- src/Views/FormPages/PersonalInfo.jsx
Ticket: [Vote-2847](https://cm-jira.usa.gov/browse/VOTE-2847)
Description: Updating screen reader labels with new spanish string translations 
Testing: 
1. Review files changed and ensure that the right translation are made 
2. Navigate to the personal info page and do a search in the DOM for the string `Voter Contact` and ensure it is present and sill hidden to trap bots that might crawl that page
> Vote-2847: Update to Spanish Strings for screen readers

- src/Views/Eligibility.jsx
Ticket: https://cm-jira.usa.gov/browse/VOTE-2854
Test steps:
1. npm run dev
2. On the first page, run WAVE and confirm the errors for the eligibility checkbox are no longer present.
3. Test the eligibility checkbox using a screenreader
> VOTE-2854 Replace the duplicate eligibility checkbox label

- src/Components/FieldContainer.jsx
- src/Components/FieldsetContainer.jsx
- src/Views/FormPages/Confirmation.jsx
- src/Views/FormPages/Identification.jsx
Ticket: [Vote-3115](https://cm-jira.usa.gov/browse/VOTE-3115)
Purpose: This pr will add `aria-live` to error messages 
Testing:
1. start local and trigger an error while having voice over on and confirm that the error message is being read out loud
Follow up work will need to update error message to have `Error:` before
> Vote-3115: adding aria-live for error text

- testing/README.md
Adding Testing Documentation to the Testing Folder
> Vote-3219: Adding Testing Readme file

- .circleci/config.yml
https://cm-jira.usa.gov/browse/VOTE-2130
Remove the Update PDF workflow. This job has been commented out for awhile, so it will be removed permanently now.
Confirm the Update PDF workflow does not show up as a job in circleci and confirm the cypress tests run and pass.
> VOTE-2310 Remove update PDF workflow

- src/Views/FormPages/Addresses.jsx
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-2856
1. Added a fieldset for the two address checkboxes.
2. Changed the help text markup to be a legend.
Test steps:
1. Select the "change registration path"
2. Move forward to the address page and turn on a screen reader.
3. Navigate to the checkboxes and confirm the screen reader indicates the checkboxes as part of a group.
4. Confirm the help text reads out for the group.
> VOTE-2856 Add missing field set and legend for address checkboxes

- src/Components/FieldComponents/TextInputField.jsx
Ticket: https://cm-jira.usa.gov/browse/VOTE-3316
Description: A field's error message was annouced right after the label, and before any user input.
This ticket sets the allyAnnouce variable to be initialized as the hint text, even when empty. The error text is the aria label only is the error is present.
Test steps:
1. Navigate to the Personal info page and turn on a screen reader.
2. Tab to first name. Confirm the label is read, but not the error message.
3. Tab to the next field without entering any data.
4. Confirm the middle name label and help text is read out.
5. Tab back to first name. Confirm the error message is announced by the screen reader. Move on without entering any data.
6. Click the next button. Confirm the screen reader takes you to first name reads out the error …
> VOTE-3316 Bug Fix: Error text announced by screenreader before input

- src/Components/ProgressBar.css
- src/Components/ProgressBar.jsx
Jira ticket: https://cm-jira.usa.gov/browse/VOTE-2858
Add underline to the link text within the step indicator.
Test steps:
1. Fill out the form, and on each page, confirm the previous completed steps now have underlined text.
2. Confirm the underlines are removed on the last page (the links are no longer enabled for complete steps after PDF generation)
> VOTE-2858 Add underline to enabled links in step indicator

- src/VoteError.css
https://cm-jira.usa.gov/browse/VOTE-3476
This should have no change in the styling of the edit buttons on the confirm page.
> VOTE-3476: enforce small button css

- testing/cypress.config.js
- testing/cypress/support/e2e.js
- testing/package-lock.json
- testing/package.json
Ticket: https://cm-jira.usa.gov/browse/VOTE-3462
Uninstall mochawesome reporter. This should resolve the [dependabot security alert](https://github.com/usagov/vote-gov-nvrf-app/security/dependabot/22).
Test steps:
cd into /testing
npm install
Confirm mochawesome report is uninstalled and there is no dependency to serialize-javascript@6.0.0.
> VOTE-3462 Uninstall mochawesome reporter
